-----------View_DIM_STORE--,

create view View_DIM_STORE as
select dimstoreid,
DIMLOCATIONID,
SOURCESTOREID,
STORENUMBER,
STOREMANAGER
from DIM_STORE

-------DIM_CUSTOMER----------

create view View_DIM_CUSTOMER as
select DIMCUSTOMERID,
DIMLOCATIONID,
SOURCECUSTOMERID,
CUSTOMERFULLNAME,
CUSTOMERFIRSTNAME,
CUSTOMERLASTNAME,
CUSTOMERGENDER
from DIM_CUSTOMER


-----DIM_RESELLER------
create view view_DIM_RESELLER
as
select DIMRESELLERID,
DIMLOCATIONID,
SOURCERESELLERID,
RESELLERNAME,
CONTACTNAME,
PHONENUMBER,
EMAIL
from DIM_RESELLER

-----------DIM_PRODUCT-------
create view VIEW_DIM_PRODUCT
as
select DIMPRODUCTID,
PRODUCTID,
PRODUCTTYPEID,
PRODUCTCATEGORYID,
PRODUCTNAME,
PRODUCTTYPE,,

PRODUCTCATEGORY,
PRODUCTRETAILPRICE,
PRODUCTWHOLESALEPRICE,
PRODUCTCOST,
PRODUCTRETAILPROFIT,
PRODUCTWHOLESALEUNITPROFIT,
PRODUCTPROFITMARGINUNITPERCENT
from DIM_PRODUCT


-------------DIM_LOCATION-----------
create view view_DIM_LOCATION
as 
select DIMLOCATIONID,
ADDRESS,
CITY,
POSTALCODE,
STATE_PROVINCE,
COUNTRY
from DIM_LOCATION


-------DIM_CHANNEL-------
create view view_DIM_CHANNEL as 
select DIMCHANNELID,
SOURCECHANNELID,
SOURCECHANNELCATEGORYID,
CHANNELNAME,
CHANNELCATEGORY
from DIM_CHANNEL


-----------dim_date----------
create view view_dim_date as 
select DATE_PKEY,
DATE,
FULL_DATE_DESC,
DAY_NUM_IN_WEEK,
DAY_NUM_IN_MONTH,
DAY_NUM_IN_YEAR,
DAY_NAME,
DAY_ABBREV,
WEEKDAY_IND,
US_HOLIDAY_IND,
_HOLIDAY_IND,
MONTH_END_IND,
WEEK_BEGIN_DATE_NKEY,
WEEK_BEGIN_DATE,
WEEK_END_DATE_NKEY,
WEEK_END_DATE,
WEEK_NUM_IN_YEAR,
MONTH_NAME,
MONTH_ABBREV,
MONTH_NUM_IN_YEAR,
YEARMONTH,
QUARTER,
YEARQUARTER,
YEAR,
FISCAL_WEEK_NUM,
FISCAL_MONTH_NUM,
FISCAL_YEARMONTH,
FISCAL_QUARTER,
FISCAL_YEARQUARTER,
FISCAL_HALFYEAR,
FISCAL_YEAR,
SQL_TIMESTAMP,
CURRENT_ROW_IND,
EFFECTIVE_DATE,
EXPIRATION_DATE
from dim_date